### ISSUE TITLE
Update plugin to latest version 1.21.3

### ISSUE THREAD

**Issue by Limitrious** [TetraTheta/HardPlus#16]
I loved this plugin, please update it to 1.21.3

**Comment by TetraTheta** [comment]
Since 1.21.4 came out, I'll wait for Paper 1.21.4 comes out, then update. I'll open this issue until I update the plugin.

**Comment by TetraTheta** [comment]
Hmm. [PaperMC announced hard fork](https://forums.papermc.io/threads/the-future-of-paper-hard-fork.1451/) and said it would take few weeks for 'stabilization'.

Since this includes changes of tools I have to use, I'll wait for the 'stabilization' and proceed. This is kind of unexpected news.

**Comment by TetraTheta** [comment]
New version (v2.6.1) is just released in both Modrinth and Hangar.

Please note that Paper for Minecraft v1.21.4 is still experimental.
